#!/bin/sh

# This hook script is to be executed by a git "update" hook used for deployment:
# https://raw.githubusercontent.com/bnf/giddyup/master/update-hook
#
# It is executed after the deployed version is activated (symlinked from "current")
# That means this script may operate on the live database.

# If the server is using fastcgi, specifiy the fcgi socket here (used for opcache clearing)
FCGI_PATH=/run/php-fpm/fcgi.sock

[[ -w "$FCGI_PATH" ]] && ${RELEASE}/vendor/bin/cachetool opcache:reset --fcgi=$FCGI_PATH || true
[[ -w "$FCGI_PATH" ]] && ${RELEASE}/vendor/bin/cachetool apcu:cache:clear --fcgi=$FCGI_PATH || true

# flush cached if we've a configured installation
[[ -e "${RELEASE}/web/typo3conf/LocalConfiguration.php" ]] && ${RELEASE}/vendor/bin/typo3cms cache:flush || true
