#!/bin/sh

# This hook script is to be executed by a git "update" hook used for deployment:
# https://raw.githubusercontent.com/bnf/giddyup/master/update-hook
#
# It is executed after the deployed version is checked out to a new folder, 
# but before the new version is activated (symlinked from "current").
# We use this script to prepare the new installation (composer install)

cd "${RELEASE}"

mkdir -p ${ROOT}/shared/web/fileadmin
share web/fileadmin
mkdir -p ${ROOT}/shared/web/uploads
share web/uploads

mkdir -p ${ROOT}/shared/web/typo3conf/l10n
share web/typo3conf/l10n
share web/typo3conf/LocalConfiguration.php


curl -sO https://getcomposer.org/download/1.3.1/composer.phar
# Or if curl is not available: wget -q https://getcomposer.org/download/1.3.1/composer.phar -O composer.phar
chmod +x composer.phar

./composer.phar install --no-dev --ansi --no-interaction --no-progress --optimize-autoloader --classmap-authoritative
