#!/bin/sh

COMPOSER_VERSION=1.3.1

# This hook script is to be executed by a git "update" hook used for deployment:
# https://raw.githubusercontent.com/bnf/giddyup/master/update-hook
#
# It is executed after the deployed version is checked out to a new folder,
# but before the new version is activated (symlinked from "current").
# We use this script to prepare the new installation (composer install)

cd "${RELEASE}"

# Preserve commit times. We want unchanged resources, e.g. style.css to not have their modification time changed
# (needed for consistent cache invalidation timestamps in urls)
git --git-dir="${REPO}" log --pretty=%ct --name-status "${NEWREV}" | \
	perl -ane '($x,$f)=@F;next if !$x;$t=$x,next if !defined($f);next if $s{$f};$s{$f}=utime($t,$t,$f) if $x=~/[AMCR]/;'

# This is not required, but nice for debugging to know which release
# belongs to which git sha1 (as that information would be lost otherwise).
echo "${NEWREV}" > SHA1

mkdir -p web/fileadmin web/uploads
share web/fileadmin
share web/uploads

# Share paths where generates resources are stored
# (as deployment may happen between resource generation and download, in that situation
# non shared resources would happen in unavailable resources)
for d in logs pics online_media sprites _processed_ GraphicalAssets GB Assets compressor RteHtmlArea Language locks swap_locking
do
	mkdir -p "web/typo3temp/${d}"
	share "web/typo3temp/${d}"
done


if [ "`composer --version 2>/dev/null | cut -d ' ' -f 3`" = "$COMPOSER_VERSION" ]
then
	COMPOSER=composer
else
	# Or if curl is not available: wget -q "https://getcomposer.org/download/$COMPOSER_VERSION/composer.phar" -O composer.phar
	curl -LOs "https://getcomposer.org/download/${COMPOSER_VERSION}/composer.phar"
	chmod +x composer.phar
	COMPOSER=./composer.phar
fi

$COMPOSER install --no-dev --ansi --no-interaction --no-progress --optimize-autoloader --classmap-authoritative --prefer-dist
vendor/bin/typo3cms extension:setupactive
